### PR TITLE
fix: custom path derivation with known network

### LINKED ISSUE #507: Custom path derivation with a known network add an extra path
How to reproduce:

Select any identity -> Add network account -> Create Custom Path -> on path input use "//kusama" as prefix

Then the path created will be prefixed with "//kusama//kusama"

|incorrect behavior| expected correct behavior|
|---|---|
|out|out|

### PR DESCRIPTION
**Pull request by hanwencheng**
closes #507 .

It works as same as expected behaviour in the issue description.

### CODE REVIEW

File: src/screens/PathDerivation.js [hunk 1]
```diff
@@ -43,22 +43,20 @@ function PathDerivation({ accounts, navigation }) {
...
+	const completePath = isCustomPath
+		? derivationPath
+		: `${currentNetworkPath}${derivationPath}`;
 
 	const onPathDerivation = async () => {
 		if (!validateDerivedPath(derivationPath)) {
 			return setIsPathValid(false);
 		}
 		const seedPhrase = await unlockSeedPhrase(navigation);
+		console.log('complete path is', completePath, 'networkKey:', networkKey);
```
Comment (Tbaut) [inline src/screens/PathDerivation.js]: stray log
