### PR TITLE
fix: add whitespace after tapping the suggestion text

### LINKED ISSUE #529: Add a white space when clicking on a proposed mnemonic word
When entering a mnemonic:
- a white space should be added automatically after the word
- the mnemonic should be trimmed from ending white space before being checked

### PR DESCRIPTION
**Pull request by hanwencheng**
close #529 .

Now after tapping the suggestion text, the trailing space will be automatically added.

And for a 24 words recovery phrase, it will not add the whitespace to the end.

But for a 12, 15, 18, or 21 words (They should all be possible to be recovered), the trailing whitespace is still added, but after tapping the "Recover Identity" button and input PIN, it will automatically be trimmed.

Test cases:
1. tapping any suggestion word, a whitespace should follow.
2. move the cursor to middle, and add another suggestion word, no extra trailing whitespace in the end should be added.
3. After input bip39 mnemonic phrase, the box border should not be red though there is a trailing whitespace.
4. after  input bip39 mnemonic phrase and recovered the identity, the recover phrase should not include any trailing whitespace, they should be removed during recovery process.
5. After input 24 bip39 words, there should be no more traling whitespaces added.

### CODE REVIEW

File: src/util/account.js [hunk 1]
```diff
@@ -72,17 +72,19 @@ export function validateSeed(seed, validBip39Seed) {
...
 		return {
 			accountRecoveryAllowed: false,
+			bip39: false,
 			reason: 'A seed phrase is required.',
 			valid: false
 		};
 	}
 
-	const words = seed.split(' ');
+	const words = validBip39Seed ? seed.trimEnd().split('') : seed.split(' ');
```
Comment (sjeohp) [inline src/util/account.js]:
```suggestion
	const words = validBip39Seed ? seed.trim().split(' ') : seed.split(' ');
```

File: src/screens/IdentityNew.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ function IdentityNew({ accounts, navigation }) {
 	const onSeedTextInput = inputSeedPhrase => {
 		setSeedPhrase(inputSeedPhrase);
 		const addressGeneration = () =>
-			brainWalletAddress(inputSeedPhrase)
+			brainWalletAddress(inputSeedPhrase.trimEnd())
```
Comment (sjeohp) [inline src/screens/IdentityNew.js]: Can `trimEnd` be removed here and below if `trim` is used in `onPress` above? If so it would be better to do it in just the one place.

File: src/screens/IdentityNew.js [hunk 3]
```diff
@@ -74,7 +74,11 @@ function IdentityNew({ accounts, navigation }) {
 	const onRecoverIdentity = async () => {
 		const pin = await setPin(navigation);
 		try {
-			await accounts.saveNewIdentity(seedPhrase, pin);
+			if (isSeedValid.bip39) {
+				await accounts.saveNewIdentity(seedPhrase.trimEnd(), pin);
```
Comment (sjeohp) [inline src/screens/IdentityNew.js]: Same as above

File: src/components/AccountSeed.js [hunk 4]
```diff
@@ -112,8 +112,9 @@ export default class AccountSeed extends Component {
 						<TouchableItem
 							key={i}
 							onPress={e => {
-								const phrase = left.concat(suggestion, right).join(' ');
-
+								let phrase = left.concat(suggestion, right).join(' ');
```
[the remark this answers is not in the document]
Comment (hanwencheng) [reply src/components/AccountSeed.js]: User could still use whitespace with brain wallet, for example, user could use `  sparta arrow`, but when user taping the `arrow`, the heading whitespace will be trimed, we should avoid to make any changes to the `left` part here.

File: src/util/account.js (hunk 1 above)
Comment (hanwencheng) [reply src/util/account.js]: If it is a validBip39Seed, it should not has already be validated by [line 65](https://github.com/paritytech/parity-signer/pull/531/files#diff-d1d34e6b6d649b5a460b1bf20a221d1eR65). So there is no heading whitespaces for seed if it is validBip39Seed.

Comment (hanwencheng) [reply src/util/account.js]: second one is true, I missed the whitespace in `split` function

Comment (sjeohp) [reply src/util/account.js]: I think `.split(' ')` is the more important change here

File: src/components/AccountSeed.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (sjeohp) [reply src/components/AccountSeed.js]: What about `trimEnd` then instead?

[the remark this answers is not in the document]
Comment (hanwencheng) [reply src/components/AccountSeed.js]: It indeed prevent the extra space when tapping the word in the middle like in the following situation. Is that the one you are concern? 
out
