### PR TITLE
Fix keyboard aware scroll view related problem

### LINKED ISSUE #278: Double tap needed in scrollview
How to reproduce (on Android not sure about iOS):
- recover an account
- tap the "name" field to enter a name.
- top the "next step" button..  you need to tap it twice.

It happens on account creation as well and sometimes when choosing network.

This has been introduced here https://github.com/paritytech/parity-signer/pull/272#pullrequestreview-264780795 and is linked to the use of `ScrollView` and potentially `KeyboardAwareScrollView`. 

I was unlucky trying things like described [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view#android-support), [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/233#issuecomment-379583908) or everywhere on the internet with `keyboardDismissMode` and `keyboardShouldPersistTaps="always"`

This scroll things needs love.

### PR DESCRIPTION
**Pull request by hanwencheng**
fix #278 

* 96c3539: fix double tap problem on Android and half covered text input on iOS related to

 #268
* 10e97b4: every click on seed input field will trigger scroll 
* 0d29f30: align seed input to top on android, so iOS and Android are same now
* b40b6da: prettier the code and remove useless import

Screenshots here (too big cannot upload on Github):  
https://drive.google.com/file/d/1g-o_XmShquI9U52agOQUl4VBX9jBujOE/view

### CODE REVIEW

File: src/screens/AccountRecover.js [hunk 1]
```diff
@@ -17,8 +17,13 @@
...
 
 import React from 'react';
-import { Alert, SafeAreaView, ScrollView, StyleSheet, Text } from 'react-native';
-import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'
+import {
+  Alert,
+  SafeAreaView,
+  StyleSheet,
+  Text,
+  findNodeHandle
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: (nit) alphabetical order, `findNodeHandle` should be placed right after `Alert`

File: src/screens/AccountRecover.js [hunk 2]
```diff
@@ -31,8 +36,9 @@ import TextInput from '../components/TextInput';
 import { NETWORK_LIST } from '../constants';
 import AccountsStore from '../stores/AccountsStore';
 import { validateSeed } from '../util/account';
-import { debounce } from '../util/debounce'
+import { debounce } from '../util/debounce';
 import { brainWalletAddress } from '../util/native';
+import KeyboardScrollView from '../components/KeyboardScrollView';
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: (nit) alphabetical order, because the import is from `../components/KeyboardScrollView`, it should be placed after `./components/Button`

File: src/components/AccountSeed.js [hunk 3]
```diff
@@ -132,6 +132,7 @@ export default class AccountSeed extends Component {
           style={[styles.input, invalidStyles]}
           multiline
           autoCapitalize="none"
+          textAlignVertical="top"
```
Comment (Tbaut) [inline src/components/AccountSeed.js]: Is this really needed? I think it looks better when the text is centred.

File: src/screens/AccountRecover.js [hunk 4]
```diff
@@ -53,124 +59,121 @@ class AccountRecoverView extends React.Component {
...
+
+  componentWillUnmount = function() {
     // called when the user goes back, or finishes the whole recovery process
-    this.props.accounts.updateNew({seed : ''});
-  }
+    this.props.accounts.updateNew({ seed: '' });
+  };
 
   render() {
     const { accounts } = this.props;
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: (nit), it's not from your PR, but as I see it..
```suggestion
    const { accounts, navigation } = this.props;
```

File: src/screens/AccountRecover.js [hunk 5]
```diff
@@ -53,124 +59,121 @@ class AccountRecoverView extends React.Component {
...
+              );
+
+              if (!validation.valid) {
+                if (validation.accountRecoveryAllowed) {
+                  return Alert.alert('Warning:', `${validation.reason}`, [
+                    {
+                      text: 'I understand the risks',
+                      style: 'default',
+                      onPress: () => {
+                        this.props.navigation.navigate('AccountPin', {
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: not needed anymore (see previous comment)
```suggestion
                        navigation.navigate('AccountPin', {
```

File: src/screens/AccountRecover.js [hunk 6]
```diff
@@ -53,124 +59,121 @@ class AccountRecoverView extends React.Component {
...
+                          isWelcome: this.props.navigation.getParam(
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: not needed anymore (see previous comment)
```suggestion
                          isWelcome: navigation.getParam(
```

File: src/screens/AccountRecover.js [hunk 7]
```diff
@@ -53,124 +59,121 @@ class AccountRecoverView extends React.Component {
...
-                  isWelcome: this.props.navigation.getParam('isWelcome'),
-                  isNew: true
-                });
-              }}
-            />
-          </ScrollView>
-        </KeyboardAwareScrollView>
+              }
+
+              this.props.navigation.navigate('AccountPin', {
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: same here
```suggestion
              navigation.navigate('AccountPin', {
```

File: src/screens/AccountRecover.js [hunk 8]
```diff
@@ -53,124 +59,121 @@ class AccountRecoverView extends React.Component {
...
+                isWelcome: this.props.navigation.getParam('isWelcome'),
```
Comment (Tbaut) [inline src/screens/AccountRecover.js]: and here
```suggestion
                isWelcome: navigation.getParam('isWelcome'),
```

File: src/components/AccountSeed.js (hunk 3 above)
Comment (hanwencheng) [reply src/components/AccountSeed.js]: Basic idea is to keep the design keep the same in both Android and iOS. Tried "alignment" to the middle, it will cause the scroll view to first move up, and move a little down after the first keystroke. I do not have a preference regarding the position, so I will just choose the one without issues then.

**Comment by hanwencheng** [comment]
YJ gave the iphone to me, I will test it later today.

**Comment by hanwencheng** [comment]
out

Tested on iPhone, looks good.
