### PR TITLE
fix: Transaction parser

### LINKED ISSUE #739: Bonding transaction not parsed
Regular bonding procedure does not display sufficient number of details

https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-polkadot

### PR DESCRIPTION
**Pull request by Slesarew**
This PR closes #739 and many similar issues, but makes thing slightly uglier.

### CODE REVIEW

File: src/modules/sign/components/PayloadDetailsCard.tsx [hunk 1]
```diff
@@ -175,58 +173,16 @@ const ExtrinsicPart = withRegistriesStore<ExtrinsicPartProps>(
...
-								the following arguments:
-							</Text>
-							{paramArgs ? (
-								paramArgs.map(([param, arg]) => (
-									<View key={param} style={styles.callDetails}>
-										<Text style={styles.titleText}>
-											{' { '}
-											{param}:{' '}
-											{arg && arg.length > 50
-												? shortString(arg)
```
Comment (Tbaut) [inline src/modules/sign/components/PayloadDetailsCard.tsx:213]: I spend some time achieve the same on Stylo, although to be able to show the whole decoded payload, all I needed was to ditch this `shortString`, which was effectively shortening valuable information.

**Comment by Tbaut** [comment]
Also FYI, in case you want to do something similar at some point, when we're signing an extrinsic whose payload length is > 256, this is considered `oversized`, and we end up only signing the hash of the Tx. Now on Signer, although we do have the info about the payload, we don't show it at all, all we show is the hash of the extrinsic that we are signing. I've removed this limitation in https://github.com/stylo-app/stylo/commit/a2f9f3b87f930b64e3d9c6d15669a79f67f64736 and not only can we show the whole payload (which is the goal of this PR afaiu), but we can also show what we're signing even if it's oversized. And of course, you still only sign the hash of the Tx.

**Comment by Slesarew** [comment]
Let's merge this as is, we'll have another PR branch to make this pretty.
