### PR TITLE
QR Code Scanner Fixes

### LINKED ISSUE #247: Show a friendly message if an address is scanned
from #245 

Users might be used to wallet applications that allow to scan a receiver's address to send funds to. Instead of showing a general error message, we can show a dedicated  message if we detect that the QR code is in the form `0x...` (20 bytes) or `ethereurm:0x..` such as:

> **Ethereum address detected**
You need to create a transaction using a software such as MyCrypto or Fether so that Parity Signer can sign it.

### PR DESCRIPTION
**Pull request by hanwencheng**
fix #247 

mainly 3 fixes:

a15259d: fix a scanning user UX issue, after unavailable QR code, only trigger the scan when the user clicks the button.

out mp4

b5e239f: add address detected warning.

eaf9f52: remove an unhandled promise rejection warning, code should return when error detected.

### CODE REVIEW

File: src/util/decoders.js [hunk 1]
```diff
@@ -189,28 +205,34 @@ export function decodeToString(message: Uint8Array): string {
 
 export function asciiToHex(message: string): string {
   var result = [];
-	for (let i = 0; i < message.length; i++) {
-		var hex = Number(message.charCodeAt(i)).toString(16);
-		result.push(hex);
+  for (let i = 0; i < message.length; i++) {
+    var hex = Number(message.charCodeAt(i)).toString(16);
```
Comment (yjkimjunior) [inline src/util/decoders.js]: grumbling at myself: 
```suggestion
    let hex = Number(message.charCodeAt(i)).toString(16);
```

File: src/util/decoders.js [hunk 2]
```diff
@@ -189,28 +205,34 @@ export function decodeToString(message: Uint8Array): string {
...
+  return result.join('');
 }
 
 export function hexToAscii(hexBytes: Uint8Array): string {
-	var hex  = hexBytes.toString();
-	var str = '';
-	for (var n = 0; n < hex.length; n += 2) {
-		str += String.fromCharCode(parseInt(hex.substr(n, 2), 16));
-	}
+  var hex = hexBytes.toString();
```
Comment (yjkimjunior) [inline src/util/decoders.js]:
```suggestion
  let hex = hexBytes.toString();
```

File: src/util/decoders.js [hunk 3]
```diff
@@ -189,28 +205,34 @@ export function decodeToString(message: Uint8Array): string {
...
+  var str = '';
```
Comment (yjkimjunior) [inline src/util/decoders.js]:
```suggestion
  let str = '';
```

File: src/util/decoders.js [hunk 4]
```diff
@@ -189,28 +205,34 @@ export function decodeToString(message: Uint8Array): string {
...
+  for (var n = 0; n < hex.length; n += 2) {
```
Comment (yjkimjunior) [inline src/util/decoders.js]:
```suggestion
  for (let n = 0; n < hex.length; n += 2) {
```

File: src/screens/QrScanner.js [hunk 5]
```diff
@@ -143,6 +160,12 @@ export class QrScannerView extends React.PureComponent {
   }
 }
 
+const text = {
+  ADDRESS_ERROR_TITLE: 'Address detected',
+  ADDRESS_ERROR_MESSAGE: 'Please create a raw transaction using a software such as MyCrypto or Fether so that Parity Signer can sign it.',
```
Comment (Tbaut) [inline src/screens/QrScanner.js]:
```suggestion
  ADDRESS_ERROR_MESSAGE: 'Please create a transaction using a software such as MyCrypto or Fether so that Parity Signer can sign it.',
```

File: src/util/decoders.js (hunk 1 above)
Comment (hanwencheng) [reply src/util/decoders.js]: Here we can use const I think, each loop is a separate block (scope), so they do not conflict with each other.

File: src/util/decoders.js (hunk 2 above)
Comment (hanwencheng) [reply src/util/decoders.js]: also `const` here?

**Comment by hanwencheng** [comment]
@Tbaut I agree, before I make the commit, I just do `prettier --write` with the file. It would be nice if we have a lint standard and to integrate the lint into CI test.

File: src/util/decoders.js (hunk 2 above)
Comment (yjkimjunior) [reply src/util/decoders.js]: yeah :[

**Comment by yjkimjunior** [comment]
works well on iOS! thank you!
